ERROR_CODES = {
  "AUTH_REQUIRED": "AUTH_REQUIRED",
  "RBAC_DENIED": "RBAC_DENIED",
  "VALIDATION_FAILED": "VALIDATION_FAILED",
  "RATE_LIMITED": "RATE_LIMITED",
  "TASK_NOT_FOUND": "TASK_NOT_FOUND",
  "DEVICE_NOT_FOUND": "DEVICE_NOT_FOUND",
  "RESULT_NOT_FOUND": "RESULT_NOT_FOUND",
  "TICKET_NOT_FOUND": "TICKET_NOT_FOUND",
  "EMPTY_CHECKLIST": "EMPTY_CHECKLIST"
}
