HazardSeverity = ["LOW","MEDIUM","HIGH","CRITICAL"]
DEFAULT_SEVERITY_BY_DEVICE_TYPE = {
  "EXTINGUISHER": "HIGH",
  "HYDRANT": "HIGH",
  "SMOKE_DETECTOR": "MEDIUM",
  "SPRINKLER": "MEDIUM",
  "EXIT_LIGHT": "LOW"
}
